version: '3'

services:
  proxy:
    build: .
    restart: unless-stopped
    ports:
     - ${PROXY_PORT}:80
    environment:
      - TARGET_URL=${TARGET_URL}
      - PROXY_PORT=${PROXY_PORT}
      - AUTH_TOKEN=${AUTH_TOKEN}
